# Generated by Django 6.0.3 on 2026-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('price_value', models.FloatField(default=0)),
                ('bhk', models.CharField(choices=[('Studio', 'Studio'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('Plot', 'Plot')], max_length=20)),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Independent House', 'Independent House'), ('Plot', 'Plot'), ('Studio', 'Studio'), ('Penthouse', 'Penthouse')], max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=20)),
                ('facing', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('living_room_360', models.URLField(blank=True, max_length=500, null=True)),
                ('kitchen_360', models.URLField(blank=True, max_length=500, null=True)),
                ('bedroom_360', models.URLField(blank=True, max_length=500, null=True)),
                ('bathroom_360', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
