# Generated by Django 6.0.3 on 2026-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
