# Generated by Django 6.0.3 on 2026-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom_360',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom_360',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen_360',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_room_360',
            field=models.TextField(blank=True, null=True),
        ),
    ]
